version: '3' 
services:
  api:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000 && python manage.py process_tasks 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"